import tkinter as tk

def create_button(master):
        Button = tk.Button(master,text=u'hist', width=5)
        Button.place(x=285,y=145)
        Button = tk.Button(master,text=u'...', width=5)
        Button.place(x=420,y=70)
        Button = tk.Button(master,text=u'...', width=5)
        Button.place(x=420,y=95)
        Button = tk.Button(master,text=u'Load Setting', width=5)
        Button.place(x=470,y=70)
        Button = tk.Button(master,text=u'RGB', width=5)
        Button.place(x=470,y=100)
        Button = tk.Button(master,text=u'NDVI', width=5)
        Button.place(x=470,y=130)
        Button = tk.Button(master,text=u'FDI', width=5)
        Button.place(x=470,y=160)
        Button = tk.Button(master,text=u'NDVI&FDI', width=5)
        Button.place(x=470,y=190)
        Button = tk.Button(master,text=u'Save Excel', width=5)
        Button.place(x=470,y=220)
        Button = tk.Button(master,text=u'Save Setting', width=5)
        Button.place(x=470,y=250)
        Button = tk.Button(master,text=u'Judge', width=5)
        Button.place(x=470,y=280)
        Button = tk.Button(master,text=u'Exit', width=5)
        Button.place(x=470,y=310)
        Button = tk.Button(master,text=u'del', width=5)
        Button.place(x=580,y=300)
        Button = tk.Button(master,text=u'load', width=5)
        Button.place(x=635,y=300)

